# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Co.Mapper
email: hola@comapper.org
description: >- # this means to ignore newlines until "baseurl:"
  Somos una comunidad de personas y organizaciones con interés en el desarrollo y mejoramiento de datos para fortalecer la resiliencia en las sociedades y gobiernos locales.
baseurl: #"comapper-website" # the subpath of your site, e.g. /blog
url: https://comapper.org/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: geoid_mx
github_username:  geoidmx


# Build settings
theme: null
#plugins:
#  - jekyll-feed

include: [_pages]

collections:
  projects:
    title: Projects
    output: true
    permalink: /proyectos/:title/
  tasks:
    title: Tasks
    output: true
    permalink: /tareas/:title/
  people:
    title: People
    output: true
    permalink: /personas/:title/

defaults:
  - scope:
      path: assets/img
    values:
      image: true
  - scope:
      path: ''
      type: projects
    values:
      layout: project
      image:
      description:
  - scope:
      path: ''
      type: tasks
    values:
      layout: task
      image:
      description:
      category:
      open_date:
      is_available:
  - scope:
      path: ''
      type: people
    values:
      layout: person
      mhoto: 
      member type:
        is staff: 
        is voting member: 
        is board member: 
      Job Title: 
      working group:
      - ''
      languages:
      - ''
      project:
      - ''
      country: 
      team: 
      social media (full url):
        OSM: 
        Twitter: 
        LinkedIn: 
        Facebook: 
        Instagram: 
        Website:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
